// ─────────────────────────────────────────────────────────────────────────────
//  Tool icon manifest — generated 3D clay squircle icons for Library tool cards.
//
//  Icons live in  public/icons/<tool_id>.webp  (512px, ~9KB each). They were
//  generated in Higgsfield (nano_banana_flash, one shared style reference so
//  the whole set matches) and harvested 2026-07-03.
//
//  Same dormant-slot philosophy as lanceVideos.ts: a tool id NOT in this set
//  simply keeps its emoji — we never request a file that isn't listed, so a
//  missing icon can't 404 or break a card. Adding a new tool's icon is:
//  drop the .webp in public/icons/, add the id here.
// ─────────────────────────────────────────────────────────────────────────────

const ICON_IDS = new Set([
  // ── THE FAMILY DECK (Foundry-cast icons landed 2026-07-11; registered
  //    2026-07-12 — they sat on disk unwired, the flagship-parity catch) ──
  'undertow_chart', 'mooring_lines', 'soundings', 'family_map', 'tide_table',
  'bottle_post', 'mending_bench', 'barometer', 'passage_chart',
  'family_manifest', 'daily_rigging', 'ships_calendar', 'sea_chest', 'ask_the_jumble',
  // ── REHABIT RECOVERY DECK (fenced addition) ──
  'urge_surfer', 'play_the_tape', 'halt_check', 'impulse_delay',
  'pros_cons_ledger', 'opposite_action', 'dbt_diary_card', 'secular_12_steps',
  'dopamine_menu', 'boundary_hoop', 'clinical_screens',
  'active_imagination',
  'activity_tracker',
  'adlerian_lab',
  'anchor_visualization',
  'anger_thermometer',
  'art_therapy',
  'assertiveness',
  'autonomic_regulation',
  'autonomic_thermostat',
  'bandura_agency',
  'behavioral_activation',
  'behavioral_lab',
  'binaural_lab',
  'biometric_mood_map',
  'biophilic_garden',
  'biopsychosocial',
  'biopsychosocial_dashboard',
  'body_scan',
  'box_breathing',
  'breathwork_478',
  'cbt_dbt_explore',
  'cbt_reframe',
  'cbt_thought_record_full',
  'character_studio',
  'client_care_hub',
  'communication_lab',
  'compassion_space',
  'coping_card_creator',
  'coping_toolkit',
  'couples_alignment',
  'cranial_nerve_gym',
  'crisis_safety_plan',
  'daily_inspiration',
  'day_at_a_glance',
  'dream_decoder',
  'eight_dimensions_wheel',
  'emdr_pacer',
  'emotion_wheel',
  'erikson_map',
  'existential_meaning',
  'fear_ladder',
  'focus_timer',
  'future_letter',
  'gestalt_chair',
  'goal_journal',
  'gratitude_log',
  'grief_space',
  'grounding_54321',
  'habit_lab',
  'habit_neuro_stacker',
  'holographic_breath',
  'ifs_parts',
  'inner_child',
  'integration_statement',
  'learning_library',
  'life_vision',
  'maslow_map',
  'mood_checkin',
  'mood_log',
  'morning_activation',
  'nutrition_mood',
  'outpost_defusion',
  'perm_gym',
  'physical_wellness',
  'polyvagal_harmonizer',
  'positive_data',
  'prefrontal_detox',
  'progressive_muscle_relaxation',
  'quests_center',
  'ras_vision_board',
  'recovery_space',
  'resilience_map',
  'rewards_store',
  'rogerian_mirror',
  'sand_tray',
  'schema_mode',
  'scream_release_room',
  'self_talk_mirror',
  'shadow_journal',
  'sleep_log',
  'smart_goals',
  'social_battery',
  'somatic_acoustic_tuner',
  'somatic_body_map',
  'somatic_breath_pacer',
  'sound_bath',
  'strengths_inventory',
  'support_finder',
  'theory_library',
  'tipp_skills',
  'transactional_analysis',
  'tremor_pacing_lab',
  'vagal_voice_analyzer',
  'values_act',
  'window_of_tolerance',
  'wise_mind',
  'worry_parking',
]);

// Resolve a tool id to its icon path, or null when the tool has no icon yet
// (caller falls back to the tool's emoji).
export function getToolIcon(toolId: string): string | null {
  return ICON_IDS.has(toolId) ? `/icons/${toolId}.webp` : null;
}
